# Generated by Django 2.2 on 2020-02-25 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_auto_20200128_1250'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='image',
            field=models.ImageField(default='no-photo.jpg', upload_to='posts/media/'),
        ),
    ]
